### ISSUE TITLE
Make an ADR template (Test/example issue)

### ISSUE THREAD

**Issue by WojtekTB** [cse110-sp23-group27/Fortune-Telling-Group-27#1]
Description of task:
Make an ADR template. Possibly in Markdown, and commit it to this repo.

Resources:
 - [Provided Canvas example](https://canvas.ucsd.edu/courses/44983/assignments/617835)
 - [Example ADR from github](https://adr.github.io/madr/)

Possible people to ask:

**Comment by ejoa27** [comment]
ADR template is located at https://github.com/cse110-sp23-group27/cse110-sp23-group27/tree/main/specs/adr
File: adr-template.md
