### ISSUE TITLE
Reset Button for Cards

### ISSUE THREAD

**Issue by daniel-lee-user** [cse110-sp23-group27/Fortune-Telling-Group-27#102]
# Describe the task:

Create a reset button for cards and when the three tarot cards are selected, allow the user to go back to the home page without opening the burger bar.

# Possible implementations/steps to take:
* Create a reset bar and hide it until the last stage of the tarot card selection
* Implement functionality similar to the home button where it takes you back to the home page and hides all elements.

# Resources:
* [Onboarding Doc](https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/blob/main/specs/documentation/onboard.md)
* [Generated Documentation](https://cse110-sp23-group27.github.io/Fortune-Telling-Group-27/specs/documentation/generated/index.html)

# Possible people to ask/assign:

TBD

**Comment by WojtekTB** [comment]
Since the change was eventually merged in a different PR I am closing this
