### ISSUE TITLE
Make GitHub button and Info Button functional

### ISSUE THREAD

**Issue by daniel-lee-user** [cse110-sp23-group27/Fortune-Telling-Group-27#108]
# Describe the task:

The GitHub button and Info button should probably open pages in a new tab. The GitHub button should open the main branch of this repo, and the text of the info button can be changed to "documentation" and it could open the JSDocs generated documentation of this repo.

# Possible implementations/steps to take:
* Implement GitHub button functionality (have it open a link in a new tab).
* Change info button text to documentation
* Add an event listener to the documentation button, have it open the generated documentation.

# Resources:
* [open a URL in a new tab](https://www.geeksforgeeks.org/how-to-open-url-in-a-new-window-using-javascript/)
* [Link to generated docs](https://cse110-sp23-group27.github.io/Fortune-Telling-Group-27/specs/documentation/generated/index.html)

# Possible people to ask/assign:

@jasonb1910

**Comment by jasonb1910** [comment]
<img width="216" alt="image" src="https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/assets/114331086/8430f05d-80c0-4696-b24c-1edeaef2c9b1">

[Updated] Changed the "Info" button to the "Documentation" button and linked to the generated docs. Also, added a functionality for the GitHub button that will open the main repo in a new tab.
