### ISSUE TITLE
Display the responses for Tarot Card

### ISSUE THREAD

**Issue by ejoa27** [cse110-sp23-group27/Fortune-Telling-Group-27#15]
# Describe the task:
When a card is clicked, the response associated with it should be displayed. The responses shown should be one of each the past, the present, and future. Text should be understandable, and lines should not vastly different character lengths.

# Possible implementations/steps to take:
* Add event listener to the card
* Find where the text has to be displayed such that different devices will have it centered and understandable.

# Resources:
* [Event Listener](https://www.w3schools.com/js/js_htmldom_eventlistener.asp)

# Possible people to ask/assign:
TBD

**Comment by daniel-lee-user** [comment]
Tarot Card responses are now properly displayed
https://cse110-sp23-group27.github.io/Fortune-Telling-Group-27/
