### ISSUE TITLE
Fix cards not matching

### ISSUE THREAD

**Issue by ejoa27** [cse110-sp23-group27/Fortune-Telling-Group-27#159]
# Describe the task:
Some cards do not fit like the rest does. So there some cards have bigger black borders, or have shorter width.

# Possible implementations/steps to take:
* Replace the images for svg files or photoshop the images.

# Resources:
* [Image sources](https://www.stickpng.com/cat/miscellaneous/tarot-cards?page=1)

# Possible people to ask/assign:
@ejoa27

**Comment by daniel-lee-user** [comment]
Fixed by this pull request https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/pull/165
