### ISSUE TITLE
Apply sound effect to the buttons , and implement speech synthesis for the card's response if possible

### ISSUE THREAD

**Issue by jasonb1910** [cse110-sp23-group27/Fortune-Telling-Group-27#166]
# Describe the task:
Currently, our application's button interactions do not include any sound effects. We need to enhance the user experience by applying sound effects to all the buttons when they are clicked or tapped. Also, add shuffling cards sound effects to the shuffle button. 

# Possible implementations/steps to take:
- Apply the "clicked" sound effect to all the buttons. 
- Add a shuffling sound effect to the shuffle button.
- Optional: Implement speech synthesis for the card's responses.
# Resources:
- [SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis)

# Possible people to ask/assign:
@jasonb1910

**Comment by jasonb1910** [comment]
[Updated] 
- Added sliding sound for the menu bar and the 3 cards selection. 
- Removed hover sounds on the homepage.
- Working on implementing speech synthesis for the card's responses.

**Comment by daniel-lee-user** [comment]
Finished with this pull request: https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/pull/167
