### ISSUE TITLE
Update Animator ADR

### ISSUE THREAD

**Issue by WojtekTB** [cse110-sp23-group27/Fortune-Telling-Group-27#201]
# Describe the task:
Update the ADR for Animator class to be up to date.

# Possible implementations/steps to take:
* Update what the Animator does now and how it functions

# Possible people to ask/assign:
@WojtekTB

**Comment by ejoa27** [comment]
Animator ADR: https://github.com/cse110-sp23-group27/cse110-sp23-group27/blob/main/specs/adr/052323-Animator.md
