### ISSUE TITLE
Implement Tarot Card Animations

### ISSUE THREAD

**Issue by kathyychenn** [cse110-sp23-group27/Fortune-Telling-Group-27#21]
# Describe the task:

Implementing card movement (hovering above when mouse hovers over, 3 cards centered after selection, etc.), rotation, flipping (revealing each card after clicking i think) and fading animations (Should allow us to animate the card fade in or out based off of some time).

# Possible implementations/steps to take:
- [x] implement card move
- [x] implement card move Instant
- [x] implement card rotate
- [x] implement card rotate instant
- [x] implement card flip
- [x] #184

# Resources:
* [Figma Design](https://www.figma.com/file/BAis5XGnwUlirl2dhi31rF/110-Wanton-Wontons---Tarot-Cards-draft?type=design&node-id=0-1&t=b6U2fwtMSdE8dzFr-0)

# Possible people to ask/assign: Team A

TBD

**Comment by WojtekTB** [comment]
Everything done except card fade that turned out to be unneeded

**Comment by ejoa27** [comment]
Card flip pull request: https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/pull/196
