### ISSUE TITLE
Implement glow/smoke CSS animations

### ISSUE THREAD

**Issue by kathyychenn** [cse110-sp23-group27/Fortune-Telling-Group-27#22]
# Describe the task:

Implement black background with moving fog smoke on the bottom half of the screen. When mouse hovers above a card, faint glow borders the card.

# Possible implementations/steps to take:

- [ ] Static black background
- [ ] Add fog/smoke moving element
- [ ] Add glow border when mouse hovers over card 

# Resources:
* [Tarot Figma](https://www.figma.com/file/BAis5XGnwUlirl2dhi31rF/110-Wanton-Wontons---Tarot-Cards-draft?type=design&node-id=0-1&t=b6U2fwtMSdE8dzFr-0)

# Possible people to ask/assign: Team A

TBD (or)
@User

**Comment by WojtekTB** [comment]
@kathyychenn @Sean-Fuhrman Could this be updated to represent the current state of the issue, and if completed fully be merged to main branch? :)
