### ISSUE TITLE
Function for New Animation Object

### ISSUE THREAD

**Issue by kathyychenn** [cse110-sp23-group27/Fortune-Telling-Group-27#23]
# Describe the task:

Write a function that creates a new animation object that holds all the information on what the animation should perform.

# Possible implementations/steps to take:
- [ ] function creates animation object with complete attributes to fully define the animation

# Resources:
* [Trello Board Task Post](https://trello.com/c/7wE1VuKM/7-animator-add-function-for-creating-a-new-animation-objects)

# Possible people to ask/assign: Team A

TBD

**Comment by WojtekTB** [comment]
unclear what this was, I will close it as it is no longer relevant
