### ISSUE TITLE
Make a functional home page

### ISSUE THREAD

**Issue by ejoa27** [cse110-sp23-group27/Fortune-Telling-Group-27#24]
# Describe the task:
Make a functional home page, possibly building off the basic home page that is able to transition to all the elements of a specific fortune telling. So choosing an option should result in only the elements of that fortune telling to be shown. i.e. choosing the tarot card option displays the tarot cards and removes anything else related to the other fortune telling types. Also add background/theme for the home page. Possibly make it so that when one hovers over one of the options, the background changes to match that fortune telling. i.e. hovering over the bone tossing option will have a grim background, while hovering over the egg option will show a more light-hearted background.

# Possible implementations/steps to take:
* Using the basic home page layout, replace the buttons for images
* If the images are able to be clicked, then implementing the hovering should also function.

# Resources:
* TBD

# Possible people to ask/assign:
@ejoa27

**Comment by jasonb1910** [comment]
<img width="648" alt="Screenshot 2023-05-30 235249" src="https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/assets/114331086/e23e78cb-4e18-4469-8167-754382c308e5">
[Updated] Replaced the buttons with images that represent tarot cards, egg, and bone tossing
