### ISSUE TITLE
Setup Automated Code Quality Review

### ISSUE THREAD

**Issue by mrkylesmith** [cse110-sp23-group27/Fortune-Telling-Group-27#26]
# Describe the task:
Add an automated code quality scoring tool to the CI/CD pipeline that will provide real-time feedback on the quality of the code that is being pushed.  

# Possible implementations/steps to take:
* Look into `Code Quality` vs `Codacy` or other code quality tools 
* Decide on a code quality tool and test it locally 
* Integrate this code quality checking into current CI/CD pipeline on `git push` and decide on how this tool fits into continuous integration pipeline loop

# Resources:
* [Code Climate](https://codeclimate.com/quality)
* [Codacy](https://github.com/marketplace/codacy)

# Possible people to ask/assign:
@mrkylesmith

**Comment by daniel-lee-user** [comment]
closed with this [pull request](https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/pull/82)
