### ISSUE TITLE
Create an ADR for coding style guidelines

### ISSUE THREAD

**Issue by ejoa27** [cse110-sp23-group27/Fortune-Telling-Group-27#3]
# Describe the task:
- Make an ADR that shows what choices we made for the coding style guidelines and formatting.

# Resources:
- [ADR References](https://adr.github.io/madr/)

# Possible people to ask/assign:
TBD

**Comment by Glekko** [comment]
https://github.com/cse110-sp23-group27/cse110-sp23-group27/tree/main/specs/adr

Link to ADRs
