### ISSUE TITLE
Apply animations to the existing Tarot Card functionality

### ISSUE THREAD

**Issue by WojtekTB** [cse110-sp23-group27/Fortune-Telling-Group-27#63]
# Describe the task:
Need to add animations such as shuffling and card selection to the card functionality already added by the team T

# Possible implementations/steps to take:
* Add shuffle animation
* add selection animation

# Resources:
* Look at the figma doc and use your imagination

# Possible people to ask/assign:
@WojtekTB

**Comment by daniel-lee-user** [comment]
This pull request added shuffling animation and a reset button https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/pull/116
