### ISSUE TITLE
Add Autoformatter to Repository 

### ISSUE THREAD

**Issue by mrkylesmith** [cse110-sp23-group27/Fortune-Telling-Group-27#8]
# Describe the task:
- Add an Autoformatter to the repository that can be run locally to ensure that developers commits will match most of the style checking enforced by the linter that is run in GitHub Action upon pushing a commit.  

# Possible implementations/steps to take:
* Do some background research or ask about a recommended autoformatter to use that works with `JS`, `HTML` and/or `CSS`. Must be able to use with multiple editors (eg. Vim, VScode) 
* Once decided on autoformatter to use, write up the formatting style in the automatter's given configuration file. 
* Commit conf file to the repo, with some documentation instructions for how to use it. 

# Resources:
* [ESLint](https://eslint.org/)

# Possible people to ask/assign:
@ejoa27

**Comment by daniel-lee-user** [comment]
You can run ESLint locally by running the command `npm run lint`. Install required dependencies first using `npm ci`.

View this [document](https://github.com/cse110-sp23-group27/Fortune-Telling-Group-27/blob/main/specs/documentation/onboard.md) for more details.
