### ISSUE TITLE
Convert PNG card images to SVGs 

### ISSUE THREAD

**Issue by mrkylesmith** [cse110-sp23-group27/Fortune-Telling-Group-27#84]
# Describe the task:
Convert all Tarot card and logo images from PNG to SVG format for higher quality images on site.

# Possible implementations/steps to take:
* Identify which images can directly be saved as SVGs
* For images we can only find PNGs of, find a PNG to SVG converter and use this.
* Replace all the PNG images with SVGs and check the quality. 

# Resources:
* [PNG to SVG Converter](https://pixelied.com/convert/png-converter/png-to-svg)
* [Adobe PNG to SVG Converter](https://www.adobe.com/express/feature/image/convert/png-to-svg)

# Possible people to ask/assign:
@mrkylesmith

**Comment by ejoa27** [comment]
Not needed anymore. Images have been adjusted to correct positions and size.
