### ISSUE TITLE
Move Trello Tasks to GitHub Issues

### ISSUE THREAD

**Issue by daniel-lee-user** [cse110-sp23-group27/Fortune-Telling-Group-27#9]
# Describe the task:

Move the tasks on the trello board for team A and team T to Github Issues

# Possible implementations/steps to take:
* Open Trello for team A and team T
* Create a GitHub issue for each task assigned

# Resources:
* [Trello Team A](https://trello.com/b/n81Dc2Ng/cse-110-110-wanton-wontons-team-a)
* [Trello Team T](https://trello.com/b/Nd0Dy9fo/cse-110-110-wanton-wontons-team-t)

# Possible people to ask/assign:

@WojtekTB

**Comment by WojtekTB** [comment]
Looks like @kathyychenn moved them over. Closing this issue now.
